### ISSUE TITLE
General Questions 

### ISSUE THREAD

**Issue by latitude35** [Esri/utilities-isolation-trace#6]
I'm working on setting up the Utility Isolation Trace app with my organization's water data and I have some questions about the app. 

I'm assuming I should be able to select any water line and it will perform a trace. When I perform a trace with the geoprocessing tool in ArcMap is it necessary to select barriers and skip locations? I don't have to in the online demo. Actually, the online demo doesn't even give you the option to select skip locations. I can select only one flag and run the demo.  If I only select a flag and run the tool, ArcMap crashes. What are skip locations? Is it necessary to select flags, barriers and skip locations and have them in the results when publishing the geoprocessing service?

Also, should I exclude hydrant valves? There is a note in the overview of the online documentation that says that because the tool will stop at every valve the hydrant valves were deleted in the published version of the water distribution network. 

Thank you for your help.

**Comment by MikeMillerGIS** [comment]
Barriers and Skip locations are optional

You can only skip a valve after you run the trace once

Skip locations allow you to bypass a valve, they work by places flags on the mains around the valve, essentially allow you to bypass it(in the case of valve stuck open)

Yes, you need to delete hydrant valves from your data and curb stops if they are in the same layer.  The find connected does not allow you only stop at a subset of the data.

This app is no longer maintained as it has been replaced with a WAB widget, info in the readme
